apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: sample-vpc1
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/18
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: default
