name: Deploy AWS Resources via Crossplane

on:
  push:
    branches:
      - main
    paths:
      - 'crossplane/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Your Linux-based runner (e.g., Ubuntu with kind)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Set KUBECONFIG for kind cluster
        run: |
          echo "Setting KUBECONFIG..."
          export KUBECONFIG="$HOME/.kube/config"
          kubectl config current-context

      - name: Apply ProviderConfig
        run: kubectl apply -f crossplane/providerconfig.yaml

      - name: Apply VPC
        run: kubectl apply -f crossplane/vpc.yaml

      - name: Apply EC2 Instance
        run: kubectl apply -f crossplane/instance.yaml
