name: AWS Resources via Crossplane

on:
  push:
    branches:
      - main
    paths:
      - 'crossplane/**'

jobs:
  deploy:
    runs-on: self-hosted  # Uses your local Windows 11 runner
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        run: |
          choco install kubernetes-cli -y
          kubectl version --client

      - name: Set KUBECONFIG (for kind)
        run: |
          echo "Setting KUBECONFIG to access kind cluster"
          $env:KUBECONFIG="$HOME\.kube\config"
          kubectl config current-context

      - name: Apply ProviderConfig
        run: kubectl apply -f crossplane/providerconfig.yaml

      - name: Apply VPC
        run: kubectl apply -f crossplane/vpc.yaml

      - name: Apply EC2 Instance
        run: kubectl apply -f crossplane/instance.yaml
